services:
  siliconflow-lb:
    image: ghcr.io/goforcex/siliconflow-lb:main
    ports:
      - "3000:3000"
    environment:
      - SILICONFLOW_BASE_URL=https://api.siliconflow.cn/v1
      - PORT=3000
      - LB_API_KEY=${LB_API_KEY}
      - LB_ADMIN_KEY=${LB_ADMIN_KEY}
    volumes:
      - ./keys.txt:/usr/src/app/keys.txt
    restart: unless-stopped
